/* CONST TYPES */

export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_CREATED_POKEMONS = 'GET_CREATED_POKEMONS'
export const GET_API_POKEMONS = 'GET_API_POKEMONS'
export const GET_POKEMON_BY_QUERY = 'GET_POKEMON_BY_QUERY'
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID'
export const GET_ALL_TYPES = 'GET_ALL_TYPES'
export const GET_FILTERED_CREATES = 'GET_FILTERED_CREATES'
export const GET_FILTERED_ASC_DES = 'GET_FILTERED_ASC_DES'
export const GET_FILTERED_TYPES = 'GET_FILTERED_TYPES'
export const DELETE_POKEMON = 'DELETE_POKEMON'
export const ERROR = 'ERROR'